"""
Admin Email Mitigation Dispatcher
=================================
Formats and sends HTML emails to the configured Admin address containing
interactive 1-Click mitigation links (Block or Dismiss).
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
import uuid
from datetime import datetime
import json

logger = logging.getLogger(__name__)

# In a production app, these would come from environment variables.
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "nithishkumarnkl2005@gmail.com"
SMTP_PASS = "czsqjbptbsrgwlnx"

# Base URL for the 1-click mitigation links
BASE_URL = "http://127.0.0.1:5000"

def send_mitigation_email(admin_email: str, target: str, level: str, score: int, details: str):
    """
    Sends a formatted HTML email to the admin with 1-click mitigation actions.
    Returns the generated action token so it can be stored in the DB if needed.
    """
    if not admin_email:
        logger.warning("No admin email configured. Skipping email dispatch.")
        return None

    # Generate a unique secure token for the action links
    action_token = str(uuid.uuid4())
    
    # Generate action URLs
    block_url = f"{BASE_URL}/api/mitigate/{action_token}/block"
    dismiss_url = f"{BASE_URL}/api/mitigate/{action_token}/dismiss"
    
    # Pick a color based on threat level
    color = "#ef4444" if level in ("High", "Critical") else "#f97316"
    
    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #f4f4f9; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
            <div style="background-color: {color}; color: white; padding: 20px; text-align: center;">
                <h2 style="margin: 0; font-size: 24px;">🚨 {level} Threat Detected</h2>
            </div>
            
            <div style="padding: 30px;">
                <p style="font-size: 16px; color: #333;"><strong>Target:</strong> {target}</p>
                <p style="font-size: 16px; color: #333;"><strong>Risk Score:</strong> {score}/100</p>
                <p style="font-size: 14px; color: #555; background: #f8fafc; padding: 15px; border-radius: 5px; border-left: 4px solid {color};">{details}</p>
                
                <h3 style="margin-top: 30px; color: #333;">Action Required:</h3>
                <p style="color: #666; font-size: 14px;">Select an action below to immediately resolve this alert via the OSINT platform.</p>
                
                <div style="margin-top: 25px; text-align: center;">
                    <a href="{block_url}" style="display: inline-block; background-color: #ef4444; color: white; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: bold; margin-right: 15px;">Block Target</a>
                    <a href="{dismiss_url}" style="display: inline-block; background-color: #e5e7eb; color: #374151; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: bold;">Dismiss Alert</a>
                </div>
            </div>
            
            <div style="background-color: #f8fafc; padding: 15px; text-align: center; color: #94a3b8; font-size: 12px;">
                Generated by OSINT ADVANTAGE Platform • {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
            </div>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Action Required: {level} Threat - {target}"
    msg["From"] = "soc@osint-advantage.local"
    msg["To"] = admin_email
    
    # Attach HTML body
    msg.attach(MIMEText(html_content, "html"))

    # For development/demo purposes without a real SMTP server configured, 
    # we will simulate the send and print the raw HTML output to the console for verification.
    try:
        if SMTP_USER and SMTP_PASS and SMTP_PASS != "REPLACE_WITH_YOUR_16_CHARACTER_APP_PASSWORD":
            with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)
            logger.info(f"✅ Successfully dispatched HTML email to {admin_email}")
        else:
            logger.warning("SMTP Password not configured! Defaulting to console print simulation.")
            logger.info(f"[MAILER SIMULATION] Dispatching HTML email to {admin_email}")
            
        logger.info(f"Generated Mitigate Action Token: {action_token}")
        
    except Exception as e:
        logger.error(f"Failed to send email to {admin_email}: {e}")
        
    return action_token
